["protostar.config"]
protostar_version = "0.7.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
account = [
    "contracts/account/PluginAccount.cairo",
]
signer = [
    "contracts/plugins/signer/StarkSigner.cairo"
]
